Update `ResponseCheckFilter` to return more human friendly error message (#8321)
In situations when the HTTP endpoint does not return a "proper" `NessieError`, for example HTTP/401 Unauthorized, the current implementation includes the stack trace of the JSON parsing exception in the _message_ of the exception. This is not useful and confusing. For example, a client that prints the full stack trace, would print _two_ stack traces: the "real" one and the one included in the exception message.

This change updates `ResponseCheckFilter` to _not_ include the `clientProcessingException` for a Jackson `MismatchedInputException`.

Example of a client that just prints `Exception.getMessage()`, which is not user frieldly. The information in the first line is all that people really need. It would contain the captured HTTP response, if there's any.
```
NessieNotAuthorizedException: Unauthorized (HTTP/401):

Additionally, the client-side exception below was caught while decoding the HTTP response:
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.projectnessie.error.ImmutableNessieError` from [Unavailable value] (token `JsonToken.NOT_AVAILABLE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2099)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1249)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1267)
	at com.fasterxml.jackson.databind.ObjectReader.treeToValue(ObjectReader.java:2044)
	at org.projectnessie.client.rest.ResponseCheckFilter.decodeErrorObject(ResponseCheckFilter.java:115)
	at org.projectnessie.client.rest.ResponseCheckFilter.checkResponse(ResponseCheckFilter.java:58)
	at org.projectnessie.client.rest.NessieHttpResponseFilter.filter(NessieHttpResponseFilter.java:29)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.lambda$executeRequest$1(JavaRequest.java:143)
	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:5186)
	at org.projectnessie.client.http.impl.jdk11.JavaRequest.executeRequest(JavaRequest.java:143)
	at org.projectnessie.client.http.HttpRequest.get(HttpRequest.java:106)
	at org.projectnessie.client.rest.v2.HttpApiV2.getConfig(HttpApiV2.java:66)
	at org.projectnessie.nessie.cli.commands.ConnectCommand.execute(ConnectCommand.java:52)
	at org.projectnessie.nessie.cli.commands.ConnectCommand.execute(ConnectCommand.java:33)
	at org.projectnessie.nessie.cli.cli.NessieCliImpl.executeCommand(NessieCliImpl.java:365)
	at org.projectnessie.nessie.cli.cli.NessieCliImpl.parseAndExecuteScript(NessieCliImpl.java:330)
	at org.projectnessie.nessie.cli.cli.NessieCliImpl.runRepl(NessieCliImpl.java:533)
	at org.projectnessie.nessie.cli.cli.NessieCliImpl.call(NessieCliImpl.java:219)
	at org.projectnessie.nessie.cli.cli.NessieCliImpl.call(NessieCliImpl.java:70)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
```