Remove Quarkus-BOM from non-Quarkus code (#4836)
The Quarkus-BOM references some dependencies that require at least
Java 11 (like `jboss-logging:3.5.0.Final`), which lets Iceberg's
Java 8 CI (and potentially other code running with Java 8) fail
with
```
java.lang.UnsupportedClassVersionError: org/jboss/logging/BasicLogger has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This change removes all references to the `quarkus-bom` from non
Quarkus related Nessie projects.