Fixes
Move code that references opentelementry classes to a separate
class to avoid NoClassDefFoundErrors. didn't happen with
opentracing, because that is unfortunately transitively present
from a ton of other libraries